name: flutter_moveable
description: This is a object moveable widget for use one to one video or audio calling, message heads like messenger etc.
version: 0.0.1
repository: https://github.com/Mohiuddin655-ORG/flutter_moveable.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: